source 'https://api.berkshelf.com'

cookbook 'build-essential'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-renv.git', :ref => 'v0.7.2'
cookbook 'nginx'
cookbook 'imagemagick'