# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
 twitter_api_key: 'NJg1Q3DlkBhIALDJIyGzBjLvl'
 twitter_api_secret: 'lWJ08IniJEkbuXTJ7kKJh4CUIxTR1Cxq9NSz1kbBnx2bRB500w'

development:
  secret_key_base: c5abc3d98ec1fa43b20d0e72f1daf541822ae13cc09d5e971f05fbb108440c85f8e02191a78c79c52c7705dac71169892d6dd7f425d00a1485bfe12259b5b992
  <<: *default_twitter

test:
  secret_key_base: 966d6155edd5936dbed7f8b50cf298f84e5757a6b7b3d3c816ff8bcaed996c42a31116bf075080fc94e253304659de12c9e86f11176c248e1825e56512632955
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
